### ISSUE TITLE
Placeholder Text

### ISSUE THREAD

**Issue by DogancanO** [DogancanO/ActivityIndicatorExample#1]
Placeholder text should disappear when the value is entered

**Comment by berkaydsaripinar** [comment]
Storyboard'da yanlışlıkla iki TextField üst üste koyulduğu için üstteki TextField'a yazarken alttaki TextField'ın placefolder yazısı gözükmeye devam ediyor. **Üstteki TextField kaldırılarak sorun çözülebilir.**

**Comment by DogancanO** [comment]
İnce tespit :) Teşekkürler.
